"""uniq user role

Revision ID: 4aefcdb88349
Revises: 9cd2069e75b3
Create Date: 2016-01-29 11:54:50.308431

"""

# revision identifiers, used by Alembic.
revision = '4aefcdb88349'
down_revision = '9cd2069e75b3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uk_user_role_user_role', 'user_roles', ['user_id', 'role_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uk_user_role_user_role', 'user_roles', type_='unique')
    ### end Alembic commands ###
