"""add pocket authorization

Revision ID: 73276e0397af
Revises: db8f9da4e9ae
Create Date: 2016-02-05 22:34:40.246559

"""

# revision identifiers, used by Alembic.
revision = '73276e0397af'
down_revision = 'db8f9da4e9ae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pocket_authorization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('access_token', sa.String(length=40), nullable=False),
    sa.Column('authorized_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='ux_pocket_authorization_user')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pocket_authorization')
    ### end Alembic commands ###
