"""set link topic_id null

Revision ID: b96dbfd1d150
Revises: 73276e0397af
Create Date: 2016-02-06 16:26:46.351332

"""

# revision identifiers, used by Alembic.
revision = 'b96dbfd1d150'
down_revision = '73276e0397af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('link', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('link', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
