"""set link topic_id nonnullable

Revision ID: db8f9da4e9ae
Revises: 81a76b1112b2
Create Date: 2016-02-04 21:13:37.222943

"""

# revision identifiers, used by Alembic.
revision = 'db8f9da4e9ae'
down_revision = '81a76b1112b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('link', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('link', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
